name: deployment CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: create .env file
      run: |
        touch .env
        echo NODE_ENV=production >> .env
        echo PORT=5000 >> .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        echo JWT_SECRET=${{ secrets.JWT_SECRET }} >> .env
        cd frontend
        touch .env
        echo HTTPS=true >> .env
        echo VITE_API_URL=${{ secrets.VITE_API_URL }} >> .env
        echo VITE_AUTH_URL=${{ secrets.VITE_AUTH_URL }} >> .env
        cd ..
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
          node-version: 18
    - run: |
       npm i
       cd frontend
       npm i
       npm run build
       cd ..
       forever start backend/app.js
       sudo service nginx restart
